version: '3.8'

services:
  image-search-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./dataset:/dataset
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    container_name: image-search-api
    runtime: nvidia
    ipc: host
    mem_limit: 14g
    cpu_count: 15
